/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package KitchenUI;
import java.util.ArrayList;
import order.*;

/**
 *
 * @author Jallais
 */
public class OrderListFrame extends javax.swing.JPanel implements OrderListView {
    private OrderListManager orderListManager;
    private MainKitchenUI mainKitchenUI;
    
    /**
     * Creates new form OrderList
     */
    public OrderListFrame(OrderListManager orderListManager, MainKitchenUI mainKitchenUI) {
        this.mainKitchenUI = mainKitchenUI;
        this.orderListManager = orderListManager;
        this.orderListManager.addView(this);
        initComponents();
    }
    
    @Override
    public void update(ArrayList<Order> orderList) {
        this.orderListPanel.removeAll();
        
        for (Order order: orderList) {
            this.orderListPanel.add(new OrderElement(order, this.mainKitchenUI));
        }
        
        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        orderListPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 0, 10, 0));
        jPanel1.setLayout(new java.awt.BorderLayout());

        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Commandes");
        jLabel1.setName("jLabel1"); // NOI18N
        jPanel1.add(jLabel1, java.awt.BorderLayout.CENTER);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        orderListPanel.setName("orderListPanel"); // NOI18N
        orderListPanel.setLayout(new javax.swing.BoxLayout(orderListPanel, javax.swing.BoxLayout.Y_AXIS));
        jPanel2.add(orderListPanel, java.awt.BorderLayout.PAGE_START);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel orderListPanel;
    // End of variables declaration//GEN-END:variables
}
