/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package KitchenUI;
import order.*;

/**
 *
 * @author Jallais
 */
public class OrderElement extends javax.swing.JPanel {
    private Order order;
    private MainKitchenUI mainKitchenUI;
    
    /**
     * Creates new form OrderElement
     */
    public OrderElement(Order order, MainKitchenUI mainKitchenUI) {
        this.mainKitchenUI = mainKitchenUI;
        this.order = order;
        initComponents();
        this.OrderNameLabel.setText(this.order.getName());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        DetailButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        OrderNameLabel = new javax.swing.JLabel();

        setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new javax.swing.BoxLayout(jPanel1, javax.swing.BoxLayout.LINE_AXIS));

        DetailButton.setText("Détails");
        DetailButton.setName("DetailButton"); // NOI18N
        DetailButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DetailButtonMouseClicked(evt);
            }
        });
        jPanel1.add(DetailButton);

        add(jPanel1, java.awt.BorderLayout.LINE_END);

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel2.setLayout(new java.awt.BorderLayout());

        OrderNameLabel.setText("jLabel1");
        OrderNameLabel.setName("OrderNameLabel"); // NOI18N
        jPanel2.add(OrderNameLabel, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void DetailButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DetailButtonMouseClicked
        this.mainKitchenUI.showOrderDetailFrame(this.order);
    }//GEN-LAST:event_DetailButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton DetailButton;
    private javax.swing.JLabel OrderNameLabel;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
