/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package KitchenUI;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import order.*;
import menu.*;
import product.*;

/**
 *
 * @author Jallais
 */
public class OrderDetailPanel extends javax.swing.JPanel {
    private Order order;
    private OrderListManager orderListManager;
    private MainKitchenUI mainKitchenUI;
    
    /**
     * Creates new form OrderDetailPanel
     */
    public OrderDetailPanel(Order order, MainKitchenUI mainKitchenUI, OrderListManager orderListManager) {
        this.orderListManager = orderListManager;
        this.mainKitchenUI = mainKitchenUI;
        this.order = order;
        initComponents();
        this.OrderNameLabel.setText(this.order.getName());
        this.setProducts();
    }
    
    private void setProducts() {
        for (Product p: this.order.getProducts()) {
            JPanel descPanel = new JPanel();
            descPanel.add(new JLabel(p.getDescription()));
            this.ProductsPanel.add(descPanel);
            
            JPanel pricePanel = new JPanel();
            pricePanel.add(new JLabel(String.format("%.2f€", p.getPrice())));
            this.PricesPanel.add(pricePanel);
        }
        
        for (Menu m: this.order.getMenus()) {
            JPanel descPanel = new JPanel();
            descPanel.add(new JLabel(m.getName()));
            this.ProductsPanel.add(descPanel);
            
            JPanel pricePanel = new JPanel();
            pricePanel.add(new JLabel(String.format("%.2f€", m.getPrice())));
            this.PricesPanel.add(pricePanel);
        }
        
        this.revalidate();
        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BackButton = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        CancelButton = new javax.swing.JButton();
        ValidateButton = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        PricesPanel = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        ProductsPanel = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        OrderNameLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setLayout(new java.awt.FlowLayout(java.awt.FlowLayout.LEFT));

        BackButton.setText("Retour");
        BackButton.setName("BackButton"); // NOI18N
        BackButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BackButtonMouseClicked(evt);
            }
        });
        jPanel1.add(BackButton);

        add(jPanel1, java.awt.BorderLayout.PAGE_START);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jPanel3.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel3.setLayout(new java.awt.GridLayout(1, 2, 10, 10));

        CancelButton.setText("Annuler");
        CancelButton.setName("CancelButton"); // NOI18N
        CancelButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CancelButtonMouseClicked(evt);
            }
        });
        jPanel3.add(CancelButton);

        ValidateButton.setText("Valider");
        ValidateButton.setName("ValidateButton"); // NOI18N
        ValidateButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ValidateButtonMouseClicked(evt);
            }
        });
        jPanel3.add(ValidateButton);

        jPanel2.add(jPanel3, java.awt.BorderLayout.PAGE_END);

        jPanel4.setLayout(new java.awt.BorderLayout());

        jPanel5.setLayout(new java.awt.BorderLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Prix (€)");
        jPanel5.add(jLabel2, java.awt.BorderLayout.NORTH);

        jPanel9.setLayout(new java.awt.BorderLayout());

        PricesPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        PricesPanel.setName("PricesPanel"); // NOI18N
        PricesPanel.setLayout(new java.awt.GridLayout(0, 1, 10, 10));
        jPanel9.add(PricesPanel, java.awt.BorderLayout.NORTH);

        jPanel5.add(jPanel9, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel5, java.awt.BorderLayout.LINE_END);

        jPanel6.setLayout(new java.awt.BorderLayout());

        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Produit(s)");
        jPanel6.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        jPanel8.setLayout(new java.awt.BorderLayout());

        ProductsPanel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        ProductsPanel.setName("ProductsPanel"); // NOI18N
        ProductsPanel.setLayout(new java.awt.GridLayout(0, 1, 10, 10));
        jPanel8.add(ProductsPanel, java.awt.BorderLayout.NORTH);

        jPanel6.add(jPanel8, java.awt.BorderLayout.CENTER);

        jPanel4.add(jPanel6, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel4, java.awt.BorderLayout.CENTER);

        jPanel7.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));

        OrderNameLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        OrderNameLabel.setText("jLabel1");
        OrderNameLabel.setName("OrderNameLabel"); // NOI18N
        jPanel7.add(OrderNameLabel);

        jPanel2.add(jPanel7, java.awt.BorderLayout.NORTH);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void BackButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BackButtonMouseClicked
        this.mainKitchenUI.showListOrderFrame();
    }//GEN-LAST:event_BackButtonMouseClicked

    private void CancelButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CancelButtonMouseClicked
        int result = JOptionPane.showConfirmDialog(this, "Annuler la commande ?");
        
        if (result == 0) {
            this.orderListManager.removeOrder(this.order);
            this.order.setState("Annulée");
            this.mainKitchenUI.showListOrderFrame();
        }
    }//GEN-LAST:event_CancelButtonMouseClicked

    private void ValidateButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ValidateButtonMouseClicked
        int result = JOptionPane.showConfirmDialog(this, "Valider la commande ?");
        
        if (result == 0) {
            this.orderListManager.removeOrder(this.order);
            this.order.setState("Terminée");
            this.mainKitchenUI.showListOrderFrame();
        }
    }//GEN-LAST:event_ValidateButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JButton CancelButton;
    private javax.swing.JLabel OrderNameLabel;
    private javax.swing.JPanel PricesPanel;
    private javax.swing.JPanel ProductsPanel;
    private javax.swing.JButton ValidateButton;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
