package BorneUI;
import javax.swing.JOptionPane;
import product.Product;
import order.*;
import menu.Menu;

public class OrderResumeFrame extends javax.swing.JPanel implements OrderView {
    private OrderManager orderManager;
    private OrderListManager orderListManager;
    private MainBorneUI main;
   /**
     * Creates new form OrderResumeFrame
     */
    public OrderResumeFrame(OrderManager orderManager, MainBorneUI main, OrderListManager orderListManager) {
        this.main = main;
        this.orderManager = orderManager;
        this.orderListManager = orderListManager;
        this.orderManager.addView(this);
        initComponents();
        this.TotalPriceLabel.setText("Total : 0€");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        ClearOrderButton = new javax.swing.JButton();
        ValidateOrder = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        ElementList = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        TotalPriceLabel = new javax.swing.JLabel();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Votre commande");
        add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.GridLayout(1, 2, 10, 0));

        ClearOrderButton.setText("Vider la commande");
        ClearOrderButton.setName("ClearOrderButton"); // NOI18N
        ClearOrderButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ClearOrderButtonMouseClicked(evt);
            }
        });
        ClearOrderButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClearOrderButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ClearOrderButton);

        ValidateOrder.setText("Valider la commande");
        ValidateOrder.setName("ValidateOrder"); // NOI18N
        ValidateOrder.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ValidateOrderMouseClicked(evt);
            }
        });
        ValidateOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ValidateOrderActionPerformed(evt);
            }
        });
        jPanel1.add(ValidateOrder);

        add(jPanel1, java.awt.BorderLayout.PAGE_END);

        jPanel2.setLayout(new java.awt.BorderLayout());

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Supprimer un élément");
        jPanel2.add(jLabel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setLayout(new java.awt.BorderLayout());

        ElementList.setName("ElementList"); // NOI18N
        ElementList.setLayout(new javax.swing.BoxLayout(ElementList, javax.swing.BoxLayout.Y_AXIS));
        jPanel3.add(ElementList, java.awt.BorderLayout.NORTH);

        jScrollPane1.setViewportView(jPanel3);

        jPanel2.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jPanel4.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 10, 0, 10));
        jPanel4.setLayout(new java.awt.BorderLayout());

        TotalPriceLabel.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        TotalPriceLabel.setText("jLabel3");
        TotalPriceLabel.setName("TotalPriceLabel"); // NOI18N
        jPanel4.add(TotalPriceLabel, java.awt.BorderLayout.CENTER);

        jPanel2.add(jPanel4, java.awt.BorderLayout.PAGE_END);

        add(jPanel2, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void ClearOrderButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ClearOrderButtonMouseClicked
        this.orderManager.clearOrder();
    }//GEN-LAST:event_ClearOrderButtonMouseClicked

    private void ValidateOrderMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ValidateOrderMouseClicked
                                           
    int result = JOptionPane.showConfirmDialog(
            this,
            String.format("Cela fait un total de %.2f€, passer commande ?", this.orderManager.getOrder().getPrice())
    );

    if (result == JOptionPane.YES_OPTION) {
        JOptionPane.showMessageDialog(this, "Merci pour votre commande, elle est en cours de préparation");
        this.orderListManager.addOrder(this.orderManager.getOrder().copy());
       Order currentOrder=this.orderManager.getOrder().copy();
       this.orderManager.clearOrder();
       main.showPaymentFrame(currentOrder);
    }


    }//GEN-LAST:event_ValidateOrderMouseClicked

    private void ClearOrderButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClearOrderButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClearOrderButtonActionPerformed

    private void ValidateOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ValidateOrderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ValidateOrderActionPerformed

    @Override
    public void update(Order order) {
        this.updateItems(order);
        this.updatePrice(order);
    }
    
    private void updateItems(Order order) {
        this.ElementList.removeAll();
        
        for (Product p: order.getProducts()) {
            this.ElementList.add(new ProductItemComponent(p, this.orderManager));
        }
        
        for (Menu m: order.getMenus()) {
            this.ElementList.add(new MenuItemComponent(m, this.orderManager));
        }
        
        this.ElementList.revalidate();
        this.ElementList.repaint();
    }
    
    private void updatePrice(Order order) {
        this.TotalPriceLabel.setText("Total : " + order.getPrice() + "€");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ClearOrderButton;
    private javax.swing.JPanel ElementList;
    private javax.swing.JLabel TotalPriceLabel;
    private javax.swing.JButton ValidateOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
