/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package BorneUI;
import order.OrderManager;
import menu.*;

/**
 *
 * @author Jallais
 */
public class SelectMenusFrame extends javax.swing.JPanel {
    private OrderManager manager;
    /**
     * Creates new form SelectMenusFrame
     */
    public SelectMenusFrame(OrderManager manager) {
        this.manager = manager;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        MenuClassiqueButton = new javax.swing.JButton();
        MenuVegetarienButton = new javax.swing.JButton();
        MenuDoubleButton = new javax.swing.JButton();

        setLayout(new java.awt.BorderLayout());

        jLabel1.setText("Menu");
        add(jLabel1, java.awt.BorderLayout.PAGE_START);

        jPanel1.setLayout(new java.awt.BorderLayout());

        jPanel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jPanel2.setLayout(new java.awt.GridLayout(1, 3, 10, 10));

        MenuClassiqueButton.setText("Menu Classique 10€");
        MenuClassiqueButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuClassiqueButtonMouseClicked(evt);
            }
        });
        jPanel2.add(MenuClassiqueButton);

        MenuVegetarienButton.setText("Menu Végétarien 11€");
        MenuVegetarienButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuVegetarienButtonMouseClicked(evt);
            }
        });
        jPanel2.add(MenuVegetarienButton);

        MenuDoubleButton.setText("Menu Double 15€");
        MenuDoubleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MenuDoubleButtonMouseClicked(evt);
            }
        });
        jPanel2.add(MenuDoubleButton);

        jPanel1.add(jPanel2, java.awt.BorderLayout.PAGE_START);

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void MenuClassiqueButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuClassiqueButtonMouseClicked
        this.manager.addMenu(new MenuClassiqueFactory().getMenu());
    }//GEN-LAST:event_MenuClassiqueButtonMouseClicked

    private void MenuVegetarienButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuVegetarienButtonMouseClicked
        this.manager.addMenu(new MenuVegetarienFactory().getMenu());
    }//GEN-LAST:event_MenuVegetarienButtonMouseClicked

    private void MenuDoubleButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MenuDoubleButtonMouseClicked
        this.manager.addMenu(new MenuDoubleFactory().getMenu());
    }//GEN-LAST:event_MenuDoubleButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton MenuClassiqueButton;
    private javax.swing.JButton MenuDoubleButton;
    private javax.swing.JButton MenuVegetarienButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
